<a href="https://colab.research.google.com/github/muxlissarajabboyeva/Pandas/blob/main/dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
data={
    'ism':['Muxlisa','Nafosat','Fotima'],
    'familiya':['Rajabboyeva','Rustambekova','Nurmetova'],
    'yosh':[22,22,22],
    'tuman':['Yangibozor','Urganch.sh','Xonqa']

}

df=pd.DataFrame(data)
print(df)

       ism      familiya  yosh       tuman
0  Muxlisa   Rajabboyeva    22  Yangibozor
1  Nafosat  Rustambekova    22  Urganch.sh
2   Fotima     Nurmetova    22       Xonqa

Xulosa: DataFrame yordamida ko'plab ustun va qatorlar yaratish mumkin.

In [4]:
df.head(2)

       ism      familiya        tyil
0  Muxlisa   Rajabboyeva  30-03-2004
1  Nafosat  Rustambekova  30-05-2004

In [6]:
df.tail(1)

      ism   familiya        tyil
2  Fotima  Nurmetova  03-01-2004

df.head() jadval boshidagi ma'lumotlarni chiqarish.default holatda boshidagi 5ta ma'lumotni chiqaradi.

df.tail() jadval oxiridagi ma'lumotlarni chiqaradi.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ism       3 non-null      object
 1   familiya  3 non-null      object
 2   tyil      3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [17]:
df['tuman']

0    Yangibozor
1    Urganch.sh
2         Xonqa
Name: tuman, dtype: object

In [18]:
df.head()

       ism      familiya  yosh       tuman
0  Muxlisa   Rajabboyeva    22  Yangibozor
1  Nafosat  Rustambekova    22  Urganch.sh
2   Fotima     Nurmetova    22       Xonqa

In [19]:
df['bosqich']=[4,4,4]
print(df)

       ism      familiya  yosh       tuman  bosqich
0  Muxlisa   Rajabboyeva    22  Yangibozor        4
1  Nafosat  Rustambekova    22  Urganch.sh        4
2   Fotima     Nurmetova    22       Xonqa        4

In [21]:
df_yangi=pd.read_csv('/content/phone_market.csv')
df_yangi.head()

,brand,model,price_usd,storage_gb,ram_gb,year,condition,sold_count
0,Samsung,Galaxy A14,150,64,4,2023,new,1200
1,Apple,iPhone 13,650,128,4,2021,used,800
2,Xiaomi,Redmi Note 12,200,128,6,2023,new,1500
3,Realme,C55,180,64,6,2023,new,1100
4,Samsung,Galaxy S22,750,256,8,2022,used,600

In [22]:
df_yangi.tail()

,brand,model,price_usd,storage_gb,ram_gb,year,condition,sold_count
3,Realme,C55,180,64,6,2023,new,1100
4,Samsung,Galaxy S22,750,256,8,2022,used,600
5,Apple,iPhone 14,800,128,6,2022,new,900
6,Xiaomi,Poco X5,230,128,6,2023,new,1300
7,Nokia,G21,160,64,4,2022,used,500

In [23]:
df_yangi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   brand       8 non-null      object
 1   model       8 non-null      object
 2   price_usd   8 non-null      int64
 3   storage_gb  8 non-null      int64
 4   ram_gb      8 non-null      int64
 5   year        8 non-null      int64
 6   condition   8 non-null      object
 7   sold_count  8 non-null      int64
dtypes: int64(5), object(3)
memory usage: 644.0+ bytes